name: 'PR Preview'
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  id-token: write

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          cache: poetry
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
      - name: Install poetry
        run: |
          python3 -m pip install -U pip poetry
      - name: Set up CDK
        run: npm install -g aws-cdk
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: CDK Deploy
        run: cdk preview --all
        env:
          LAZYBOOST_ERROR_EMAIL: ${{ secrets.LAZYBOOST_ERROR_EMAIL }}
