name: 'PR Preview'
run-name: Build initiated by ${{ github.actor }} for branch ${{inputs.branch}}
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  id-token: write
  contents: read

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/Hydrogen'
      - name: Install python dependencies
        run: poetry install --only main
      - name: Set up CDK
        run: |
          npm install -g aws-cdk
          npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_REGION: us-east-1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
      - name: CDK Diff
        run: cdk diff --all
        env:
          LAZYBOOST_ERROR_EMAIL: ${{ secrets.LAZYBOOST_ERROR_EMAIL }}
          AWS_REGION: us-east-1
