name: 'Run poetry and npm update on a schedule'
on:
  schedule:
    - cron: '15 9 * * 6' 

jobs:
  dependency-update:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          cache: poetry
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
      - name: Install poetry
        run: |
          python3 -m pip install -U pip poetry
      - name: Update dependencies
        run: |
          poetry update
          npm update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          add-paths: |
            pyproject.toml
            poetry.lock
            package.json
            package-lock.json
          commit-message: poetry and npm update
          title: workflow - poetry update
          base: main
          labels: dependencies
          branch: workflow-dependency-update
          delete-branch: true
