name: 'Run poetry and npm update on a schedule'
on:
  schedule:
    - cron: '15 10 * * 6'

jobs:
  dependency-update:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/Hydrogen'
      - name: Update dependencies
        run: |
          make dependency-update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          add-paths: |
            poetry.lock
            package-lock.json
          commit-message: dependency update
          title: workflow - dependency update
          base: main
          labels: dependencies
          branch: workflow-dependency-update
          assignees: weirdion
          delete-branch: true
