name: 'Run poetry and npm update on a schedule'
on:
  schedule:
    - cron: '15 10 * * 6'
  push:
    branches:
      - 52-update-dep-workflow

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          cache: poetry
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
      - name: Install poetry
        run: |
          python3 -m pip install -U pip poetry
      - name: Update dependencies
        run: |
          make dependency-update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          add-paths: |
            poetry.lock
            package-lock.json
          commit-message: dependency update
          title: workflow - dependency update
          base: main
          labels: dependencies
          branch: workflow-dependency-update
          author: ${{ secrets.GIT_AUTHOR_NAME }} <${{ vars.GIT_AUTHOR_EMAIL }}>
          assignees: weirdion
          reviewers: weirdion
          delete-branch: true
